# GET http://localhost:3000/users/all


# GET http://localhost:3000/users/3


POST http://localhost:3000/users/
 content-type:application/json

 {
             "type":"agent_user",
             "userName":"yusuf",
             "LastName":"hello",
             "Telefon":"3836675835",
             "email":"m@gmail.com",
             "additional":"",
             "description":""
    }

# DELETE http://localhost:3000/users/9 HTTP/1.1 
